import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'doc', id: 'intro', label: '🏠 Inicio' },  // ← Agrega esto primero
    { type: 'autogenerated', dirName: 'capitulos' },
  ],
};

export default sidebars;